version: '3.3'

services:
  filebeat:
    build:
      context: .
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
